site_name: Lingmo Wiki
theme:
  name: 'material'
  logo: img/favicon.ico
extra:
  alternate:
    - name: 简体中文
      link: /zh/
      lang: zh
    - name: English
      link: /en/ 
      lang: en
copyright: Copyright &copy; 2024 Lingmo OS
nav:
    - 简体中文: 
        - 安装教程: zh/index.md
        - 关于: zh/about.md
        - 常见问题解答: zh/faq.md
    - English: 
        - Installation: en/index.md
        - Disk-Space: en/disk_space.md
        - About: en/about.md
        - FAQ: en/faq.md